site_name: Test Documentation
site_url: https://docs-test.dkube.io/

docs_dir: docs
site_dir: site
use_directory_urls: false

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Test Page: test.md